services:
  ttp:
    build: Code/ttp
    container_name: bsk_ttp
    ports: 
    - "5000:5000"
    networks:
      bsk_net:
        ipv4_address: 172.20.0.2

  server:
    build: Code/server
    container_name: bsk_server
    ports:
      - "7000:7000"
    depends_on:
      - ttp
    networks:
      bsk_net:
        ipv4_address: 172.20.0.3

networks:
  bsk_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16